#!/bin/sh

logger -t h5000m-defaults "设置默认 LAN 地址为 192.168.10.1"
uci -q set network.lan.proto='static'
uci -q set network.lan.ipaddr='192.168.10.1'
uci -q set network.lan.netmask='255.255.255.0'

logger -t h5000m-defaults "优化 WAN 与 5G 备用出口"
uci -q set network.wan.metric='10'
uci -q set network.wan6.metric='10'

if uci -q show network.1_1 >/dev/null 2>&1; then
	uci -q rename network.1_1='wan5g'
fi

if uci -q show network.1_1v6 >/dev/null 2>&1; then
	uci -q rename network.1_1v6='wan5g6'
fi

if [ -e /sys/class/net/eth2 ] || uci -q show network.wan5g >/dev/null 2>&1; then
	uci -q set network.wan5g='interface'
	uci -q set network.wan5g.proto='dhcp'
	uci -q set network.wan5g.device='eth2'
	uci -q set network.wan5g.ifname='eth2'
	uci -q set network.wan5g.metric='50'

	uci -q set network.wan5g6='interface'
	uci -q set network.wan5g6.proto='dhcpv6'
	uci -q set network.wan5g6.device='@wan5g'
	uci -q set network.wan5g6.ifname='@wan5g'
	uci -q set network.wan5g6.metric='50'
fi
uci -q commit network

logger -t h5000m-defaults "将 5G 备用出口加入 WAN 防火墙区域"
for zone in $(uci -q show firewall | sed -n 's/^\(firewall\.[^.]*\)=zone$/\1/p'); do
	if [ "$(uci -q get "${zone}.name")" = "wan" ]; then
		uci -q del_list "${zone}.network=1_1"
		uci -q del_list "${zone}.network=1_1v6"
		uci -q del_list "${zone}.network=wan5g"
		uci -q del_list "${zone}.network=wan5g6"
		uci -q add_list "${zone}.network=wan5g"
		uci -q add_list "${zone}.network=wan5g6"
	fi
done
uci -q commit firewall

logger -t h5000m-defaults "设置 root 默认密码"
if command -v chpasswd >/dev/null 2>&1; then
	echo 'root:admin' | chpasswd
else
	(printf 'admin\nadmin\n' | passwd root) >/dev/null 2>&1 || true
fi

logger -t h5000m-defaults "设置默认 WiFi 密码"
if ! uci -q show wireless | grep -q '=wifi-iface'; then
	wifi config >/dev/null 2>&1 || true
fi

for section in $(uci -q show wireless | sed -n 's/^\(wireless\.[^.]*\)=wifi-iface$/\1/p'); do
	uci -q set "${section}.encryption=psk2"
	uci -q set "${section}.key=1234567890"
done
uci -q commit wireless

logger -t h5000m-defaults "清理固件内的 QModem 和 video 软件源"
if [ -f /etc/apk/repositories.d/distfeeds.list ]; then
	sed -i '/\/qmodem\//d;/ qmodem[ _-]/d;/ qmodem$/d;/\/video\//d' /etc/apk/repositories.d/distfeeds.list
fi

if [ -f /etc/opkg/distfeeds.conf ]; then
	sed -i '/\/qmodem\//d;/ qmodem[ _-]/d;/ qmodem$/d;/\/video\//d' /etc/opkg/distfeeds.conf
fi

exit 0
